# MIT License
# Copyright (c) 2020 Yuta Mibuchi

network:
    ethernets:
        eth0:
           dhcp4: false
           optional: false
           addresses: [192.168.1.2/24]
           gateway4: 192.168.1.1
           nameservers:
                addresses: [192.168.1.1]
           match:
                    macaddress: b8:27:eb:00:00:00
           set-name: eth0
    wifis:
        wlan0:
            dhcp4: false
            optional: false
            addresses: [192.168.1.3/24]
            gateway4: 192.168.1.1
            nameservers:
                 addresses: [192.168.1.1]
            access-points:
                    ssid1:
                        password: "password1"
                    ssid2:
                        password: "password2"
    version: 2
    renderer: NetworkManager
